# -*- coding: utf-8 -*-
"""Pandas Assignment Day 10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KKeaqXq5ZaueUg-LIbdEpGoSo9KBYI2c

# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases
"""

import pandas as pd
import numpy as np

"""Create a variable a = pd.Series([ 100, 200, 300, 400])"""

a = pd.Series([ 100, 200, 300, 400])

"""Print a, and data type"""

print(a)
print(a.dtype)

"""Using indexing access the element 300 from the series a."""

print(a[2])

"""What are the values of index for series a?"""

print(a.index)

"""Change the index to  ['c', 'a', 'b', 'd']"""

a = pd.Series([ 100, 200, 300, 40],index=['c', 'a', 'b', 'd'])

"""Access the value in the series with index 'd'"""

print(a["d"])

"""Sort the values wrt to the index and print it"""

print(a.sort_index())

"""Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it"""

b = pd.Series([800,450,100],index=["e","f","g"])

print(b)

"""Append b series at the end of a series"""

a = pd.concat([a,b])
print(a)

#print a again after appending b into it

print(a)

"""Sort the values in descending order of a and print the index of the sorted series"""

a = a.sort_values(ascending=False)
print(a)

"""## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe
"""

df = pd.DataFrame(a)
print(df)

"""What is the shape of the datafarme <br>
(also, what does it imply?)
"""

print(df.shape)

"""Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'
"""

# yep its same as the series.

print(df.index)

"""print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)
"""

print(df.head())

print(df.tail())

"""Rename the column of the dataframe as 'points'"""

df.columns = {"points"}
print(df)

"""Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']"""

#Create fruits array

fruits_array = np.random.choice(['orange','mango','apple'],size=len(df))

#Create series fruits out of fruits array

fruits = pd.Series(fruits_array)

"""Change the index of fruits to the index of dataframe df"""

fruits.index = df.index

"""Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify
"""

df["fruits"]=fruits

print(df.head())

"""## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]
"""

d1 = pd.DataFrame({"city":["Chandigarh","Delhi", "Kanpur", "Chennai", "Manali"],
                   "Temperature":[15,22,20,26,-2]})

"""Print(d1)"""

print(d1)

"""What is the shape of d1."""

print(d1.shape)

"""Set city = d1['city']"""

city = d1["city"]

"""print city <br>
What is the type of city.
"""

print(city)
print(type(city))

"""Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]
"""

d2 = pd.DataFrame({
    "city":["Bengalaru","Coimbatore","Srirangam","Pondicherry"],
    "Temperature":[24,35,36,39]
})

"""print the shape of this dataframe"""

print(d2.shape)

"""merge the two dataframes together, save it in a new dataframe named 'd3'"""

d3 = pd.concat([d1, d2])
print(d3)

"""Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?
"""

cold_cities = d3[d3['Temperature'] <= 20]
print(cold_cities)
print(f"Number of cities with temperature <= 20: {cold_cities.shape[0]}")

"""Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35"""

cold_cities =d3[d3["Temperature"]>=35]
print(cold_cities)

"""## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.
"""

# write function here

def is_ut(x):
  if x in ["Chandigarh", "Pondicherry", "Delhi"]:
    return True
  else:
    return False

#     # write code below

d3['is_ut'] = d3["city"].apply(is_ut)

# print d3
print(d3)

"""The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.
"""

# write function here


def c_to_f(x):
  return (x*9/5)+32

# check function c_to_f(10)

print(c_to_f(10))

# apply function c_to_f to d3 to create a column 'temp_farenhiet'
d3["temp_farenhiet"]=d3["Temperature"].apply(c_to_f)

"""## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.
"""

union_territories = d3[d3["city"].isin(["Chandigarh", "Pondicherry", "Delhi"])]
print(union_territories)

"""Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet."""

d1["temp_farenhiet"] = d1["Temperature"].apply(c_to_f)
hot_cities = d1[d1["temp_farenhiet"] > 90]
print(hot_cities)

"""Select only the first three rows of the dataframe d1.

"""

print(d1.iloc[0:3])

"""Select all the rows and last two columns in the dataframe.



"""

print(d1.iloc[:,-2:])

"""## Groupby"""

# Create a dataframe using dictionary of your choice

data = pd.DataFrame( {
    'Category': ['A', 'B', 'A', 'B', 'A', 'C'],
    'Value': [10, 15, 12, 18, 11, 20],
    'Quantity': [1, 2, 1, 3, 2, 1]
})

# Use Groupby of single column with aggregate sum()

print(data.groupby("Category")[["Value"]].sum())

# Use Groupby of single column with aggregate count()
print(data.groupby("Category")[["Value"]].count())

# Use Groupby of single column with aggregate min() and max()
print(data.groupby("Category")[["Value"]].min())
print(data.groupby("Category")[["Value"]].max())

# Use Groupby of any 2 columns with aggregate mean()
print(data.groupby(["Category","Value"])[["Quantity"]].mean())

# Use Groupby of any 2 columns with aggregate min() and max()
print(data.groupby(["Category","Value"])[["Quantity"]].min())

print(data.groupby(["Category","Value"])[["Quantity"]].max())

"""## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'
"""

a = pd.date_range(start="2020-01-01",end="2021-04-01")

"""print a"""

print(a)

"""What is the len of a?"""

print(len(a))

"""What is the type of a?"""

print(type(a))